AllCops:
  DisplayCopNames: true
  Exclude: 
    - ./config/**/*.rb
    - ./db/*.rb
    - Gemfile
    - Guardfile
    - ./vendor/**/*
    - ./spec/**/*
    - ./kagu/**/*

Style/Documentation:
  Enabled: false

Lint/Debugger:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false